In [ ]:
import numpy as np
grid_height = 10
grid_length = 7
wind_intensity = [0,0,0,1,1,1,2,2,1,0]
possible_actions = [(1,0),(0,1),(0,-1)] #right, up, down
start = (0,3)
goal = (7,3)
action_matrix= []


for state_x in range(grid_length):
    action_matrix.append([])
    for state_y in range(grid_height):
      action_matrix[state_x].append([])
      for action_num in range(len(possible_actions)):
        init_prob = 100

        action_matrix[state_x][state_y].append(init_prob)
action_matrix = np.array(action_matrix,dtype=np.float64)
print(action_matrix)

[[[100. 100. 100.]
  [100. 100. 100.]
  [100. 100. 100.]
  [100. 100. 100.]
  [100. 100. 100.]
  [100. 100. 100.]
  [100. 100. 100.]
  [100. 100. 100.]
  [100. 100. 100.]
  [100. 100. 100.]]

 [[100. 100. 100.]
  [100. 100. 100.]
  [100. 100. 100.]
  [100. 100. 100.]
  [100. 100. 100.]
  [100. 100. 100.]
  [100. 100. 100.]
  [100. 100. 100.]
  [100. 100. 100.]
  [100. 100. 100.]]

 [[100. 100. 100.]
  [100. 100. 100.]
  [100. 100. 100.]
  [100. 100. 100.]
  [100. 100. 100.]
  [100. 100. 100.]
  [100. 100. 100.]
  [100. 100. 100.]
  [100. 100. 100.]
  [100. 100. 100.]]

 [[100. 100. 100.]
  [100. 100. 100.]
  [100. 100. 100.]
  [100. 100. 100.]
  [100. 100. 100.]
  [100. 100. 100.]
  [100. 100. 100.]
  [100. 100. 100.]
  [100. 100. 100.]
  [100. 100. 100.]]

 [[100. 100. 100.]
  [100. 100. 100.]
  [100. 100. 100.]
  [100. 100. 100.]
  [100. 100. 100.]
  [100. 100. 100.]
  [100. 100. 100.]
  [100. 100. 100.]
  [100. 100. 100.]
  [100. 100. 100.]]

 [[100. 100. 100.]
  [100. 100. 100.]
  

In [ ]:
import random
current_state = start

for k in range(10000):
  gamma = 0.99
  current_state =  (random.randint(0,grid_length-1),random.randint(0,grid_height-1))

  for i in range(1000):
    action = random.choices(possible_actions, weights= action_matrix[current_state[0]][current_state[1]])[0]
    action_index = possible_actions.index(action)
    x_move = max(min(current_state[0] + action[0],grid_length-1),0)
    y_move = max(min(current_state[1] + action[1]+wind_intensity[x_move],grid_height-1),0)

    current_state = (x_move,y_move)

    reward = -0.01*((x_move-goal[1]-1)**2+(y_move-goal[0])**2)

    action2 = random.choices(possible_actions, weights= action_matrix[current_state[0]][current_state[1]])[0]
    action_index2 = possible_actions.index(action2)
    x_move_2 = max(min(current_state[0] + action[0],grid_length-1),0)
    y_move_2 = max(min(current_state[1] + action[1],grid_height-1),0) # no wind here
    action_matrix[x_move][y_move][action_index] = action_matrix[x_move][y_move][action_index]+0.001*(reward+gamma*action_matrix[x_move_2][y_move_2][action_index2]-action_matrix[x_move][y_move][action_index])
    action_matrix[x_move][y_move][action_index] = max(action_matrix[x_move][y_move][action_index],0.00001)
     #print(action_matrix)



In [ ]:
action_matrix

array([[[100.        , 100.        ,  99.52421051],
        [100.        ,  99.75680894,  99.79555069],
        [100.        ,  99.79649205,  99.80549421],
        [100.        ,  99.81747967,  99.82764336],
        [100.        ,  99.80963776,  99.83977854],
        [100.        ,  99.81257221,  99.82439745],
        [100.        ,  99.82810114,  99.80330854],
        [100.        ,  99.81401341,  99.80970756],
        [100.        ,  99.8399934 ,  99.81718941],
        [100.        ,  99.70414485, 100.        ]],

       [[ 99.72792964, 100.        ,  99.15320712],
        [ 99.77665089,  99.54605335,  99.59237466],
        [ 99.8191254 ,  99.61036532,  99.61231742],
        [ 99.8055063 ,  99.64006938,  99.61944681],
        [ 99.80131798,  99.62368158,  99.65026674],
        [ 99.79896259,  99.65658551,  99.67769496],
        [ 99.82216338,  99.6811991 ,  99.70196655],
        [ 99.80826528,  99.69111078,  99.71459152],
        [ 99.8398774 ,  99.68478521,  99.69225437],
        [ 

In [ ]:
best_actions = []
for x in range(grid_length):
  best_actions.append([])
  for y in range(grid_height):
    a = np.argmax(action_matrix[x][y])
    if( a==0):
      best_actions[x].append(">")
    elif(a==1):
      best_actions[x].append("^")
    else:
      best_actions[x].append("v")
best_actions = np.array(best_actions)
print(best_actions)

[['>' '>' '>' '>' '>' '>' '>' '>' '>' '>']
 ['^' '>' '>' '>' '>' '>' '>' '>' '>' 'v']
 ['^' '>' '>' '>' '>' '>' '>' '>' '>' 'v']
 ['>' '^' '^' '^' '^' '>' '^' '>' '>' 'v']
 ['>' '^' '^' '^' '^' '^' '^' '^' 'v' 'v']
 ['>' '^' '>' '^' '^' '^' '^' '^' 'v' 'v']
 ['>' '>' '^' '^' '^' '^' '^' '^' 'v' 'v']]


In [ ]:
for x in range(grid_length):
  for y in range(grid_height):

    print(-0.01*((x-goal[1]-1)**2+(y-goal[0])**2),end=";")
  print()

-0.65;-0.52;-0.41000000000000003;-0.32;-0.25;-0.2;-0.17;-0.16;-0.17;-0.2;
-0.58;-0.45;-0.34;-0.25;-0.18;-0.13;-0.1;-0.09;-0.1;-0.13;
-0.53;-0.4;-0.29;-0.2;-0.13;-0.08;-0.05;-0.04;-0.05;-0.08;
-0.5;-0.37;-0.26;-0.17;-0.1;-0.05;-0.02;-0.01;-0.02;-0.05;
-0.49;-0.36;-0.25;-0.16;-0.09;-0.04;-0.01;-0.0;-0.01;-0.04;
-0.5;-0.37;-0.26;-0.17;-0.1;-0.05;-0.02;-0.01;-0.02;-0.05;
-0.53;-0.4;-0.29;-0.2;-0.13;-0.08;-0.05;-0.04;-0.05;-0.08;


In [ ]:
goal[0]

7